
import React from 'react';
import { QuoteData, FormData } from './QuoteGenerator';
import { formatExchangeRate } from '../utils/formatters';

interface QuoteLayoutProps {
  data: QuoteData;
  formData: FormData;
  children: React.ReactNode;
}

const QuoteLayout: React.FC<QuoteLayoutProps> = ({ data, formData, children }) => {
  const currentDate = new Date().toLocaleDateString();

  return (
    <div className="quote-container space-y-8">
      {children}
      
      {/* Single instance of Important Notes with Exchange Rate */}
      <div className="important-notes rounded-lg bg-blue-50 p-6">
        <div className="space-y-4">
          <h3 className="text-blue-900 font-medium">Important Notes:</h3>
          <ul className="space-y-2 text-blue-800">
            <li>• Currency conversions based on rates on {currentDate}, may vary—contracts always in local currency.</li>
            <li>• Setup Cost = one month's salary (Security Deposit) + Ontop fee; secures Ontop against potential defaults.</li>
            <li>• Dismissal Deposit = one-twelfth of salary, provisioned for future termination costs.</li>
          </ul>
          <div className="text-sm text-blue-600">
            <p>Exchange Rate: {formatExchangeRate(data.exchangeRate)} {data.localCurrency}/USD</p>
            <p className="italic">Rates are indicative and may vary. Contracts are always processed in local currency.</p>
          </div>
          <p className="text-sm text-gray-500 mt-4">
            Generated by Ontop Quote Generator • {currentDate}
          </p>
        </div>
      </div>
    </div>
  );
};

export default QuoteLayout;
