
import React from 'react';
import { formatExchangeRate } from '../utils/formatters';

interface QuoteFooterProps {
  exchangeRate: number;
  localCurrency: string;
  currentDate: string;
}

export const QuoteFooter: React.FC<QuoteFooterProps> = ({ 
  exchangeRate, 
  localCurrency,
  currentDate 
}) => {
  return (
    <div className="quote-footer mt-8">
      <div className="rounded-lg bg-blue-50 p-6">
        <h3 className="text-blue-900 font-medium mb-3">Important Notes:</h3>
        <ul className="space-y-2 text-blue-800">
          <li>• Currency conversions based on rates on {currentDate}, may vary—contracts always in local currency.</li>
          <li>• Setup Cost = one month's salary (Security Deposit) + Ontop fee; secures Ontop against potential defaults.</li>
          <li>• Dismissal Deposit = one-twelfth of salary, provisioned for future termination costs.</li>
        </ul>
        <div className="mt-4 text-sm text-blue-700">
          <p className="font-medium">Exchange Rate: {formatExchangeRate(exchangeRate)} {localCurrency}/USD</p>
          <p className="italic">Rates are indicative and may vary. Contracts are always processed in local currency.</p>
        </div>
        <p className="text-sm text-gray-500 mt-4">
          Generated by Ontop Quote Generator • {currentDate}
        </p>
      </div>
    </div>
  );
};
