
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { QuoteData } from '../components/QuoteGenerator';

export const generatePDF = async (element: HTMLElement, data: QuoteData): Promise<void> => {
  try {
    // Create a temporary container for PDF content
    const pdfContainer = document.createElement('div');
    pdfContainer.style.width = '210mm'; // A4 width
    pdfContainer.style.minHeight = '297mm'; // A4 height
    pdfContainer.style.padding = '20mm';
    pdfContainer.style.backgroundColor = 'white';
    pdfContainer.style.fontFamily = 'Arial, sans-serif';
    pdfContainer.style.position = 'absolute';
    pdfContainer.style.top = '-9999px';
    pdfContainer.style.left = '-9999px';

    // Create PDF header with Ontop branding
    const header = document.createElement('div');
    header.innerHTML = `
      <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 30px; border-bottom: 2px solid #FF5A71; padding-bottom: 20px;">
        <div>
          <h1 style="color: #FF5A71; font-size: 32px; font-weight: bold; margin: 0;">Ontop</h1>
          <p style="color: #666; font-size: 14px; margin: 5px 0 0 0;">Global Employment Solutions</p>
        </div>
        <div style="text-align: right; background: #f8f9fa; padding: 15px; border-radius: 8px; border-left: 4px solid #FF5A71;">
          <div style="margin-bottom: 10px;">
            <label style="font-size: 12px; color: #666; display: block;">Quote Sender:</label>
            <div style="border-bottom: 1px solid #ccc; width: 150px; height: 20px;"></div>
          </div>
          <div style="margin-bottom: 10px;">
            <label style="font-size: 12px; color: #666; display: block;">Client Name:</label>
            <div style="border-bottom: 1px solid #ccc; width: 150px; height: 20px;"></div>
          </div>
          <div>
            <label style="font-size: 12px; color: #666; display: block;">Valid Until:</label>
            <div style="border-bottom: 1px solid #ccc; width: 150px; height: 20px;"></div>
          </div>
        </div>
      </div>
    `;

    // Create PDF content
    const content = document.createElement('div');
    content.innerHTML = `
      <h2 style="color: #333; font-size: 24px; margin-bottom: 20px;">Employment Quote Summary</h2>
      
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px;">
        ${createTableHTML('Amount You Pay', data.amountYouPay, '#FF5A71')}
        ${createTableHTML('Amount Employee Gets', data.amountEmployeeGets, '#10B981')}
      </div>
      
      ${data.setupSummary.length > 0 ? `
      <div style="margin-bottom: 30px;">
        ${createTableHTML('Setup Summary', data.setupSummary, '#3B82F6')}
      </div>
      ` : ''}
    `;

    // Create footer
    const footer = document.createElement('div');
    const currentDate = new Date().toLocaleDateString();
    footer.innerHTML = `
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #666; line-height: 1.4;">
        <p><strong>Important Notes:</strong></p>
        <ul style="margin: 10px 0; padding-left: 20px;">
          <li>Currency conversions based on rates on ${currentDate}, may vary—contracts always in local currency.</li>
          <li>Setup Cost = one month's salary + Ontop fee; secures Ontop against defaults.</li>
          <li>Dismissal Deposit = one-twelfth of salary, provisioned for future termination costs.</li>
          <li>All amounts are subject to final contract terms and local regulations.</li>
        </ul>
        <div style="text-align: center; margin-top: 20px; color: #FF5A71; font-weight: bold;">
          Generated by Ontop Quote Generator • ${currentDate}
        </div>
      </div>
    `;

    // Assemble PDF container
    pdfContainer.appendChild(header);
    pdfContainer.appendChild(content);
    pdfContainer.appendChild(footer);
    document.body.appendChild(pdfContainer);

    // Generate PDF
    const canvas = await html2canvas(pdfContainer, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff'
    });

    document.body.removeChild(pdfContainer);

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    const fileName = `Ontop-Quote-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(fileName);

  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

const createTableHTML = (title: string, fields: any[], color: string): string => {
  if (fields.length === 0) return '';

  const total = fields.reduce((sum, field) => sum + field.amount, 0);
  
  return `
    <div style="border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin-bottom: 20px;">
      <div style="background: ${color}; color: white; padding: 15px;">
        <h3 style="margin: 0; font-size: 18px; font-weight: 600;">${title}</h3>
      </div>
      <div style="background: white;">
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background: #f9fafb;">
              <th style="padding: 12px 15px; text-align: left; font-size: 12px; color: #374151; font-weight: 600; border-bottom: 1px solid #e5e7eb;">Description</th>
              <th style="padding: 12px 15px; text-align: right; font-size: 12px; color: #374151; font-weight: 600; border-bottom: 1px solid #e5e7eb;">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${fields.map(field => `
              <tr>
                <td style="padding: 10px 15px; font-size: 14px; color: #111827; border-bottom: 1px solid #f3f4f6;">${field.label}</td>
                <td style="padding: 10px 15px; font-size: 14px; color: #111827; text-align: right; font-weight: 500; border-bottom: 1px solid #f3f4f6;">
                  ${new Intl.NumberFormat('en-US', { style: 'currency', currency: field.currency }).format(field.amount)}
                </td>
              </tr>
            `).join('')}
            <tr style="background: #f9fafb; font-weight: 600;">
              <td style="padding: 12px 15px; font-size: 14px; color: #111827;">Total</td>
              <td style="padding: 12px 15px; font-size: 14px; color: #111827; text-align: right;">
                ${new Intl.NumberFormat('en-US', { style: 'currency', currency: fields[0]?.currency || 'USD' }).format(total)}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  `;
};
